/*
 * This file is generated by jOOQ.
 */
package org.jooq.test.tables.records;


import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.test.tables.Planets;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetsRecord extends UpdatableRecordImpl<PlanetsRecord> implements Record6<Integer, String, String, LocalDate, String, String> {

    private static final long serialVersionUID = 575223953;

    /**
     * Setter for <code>space_info.planets.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>space_info.planets.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>space_info.planets.planet_name</code>.
     */
    public void setPlanetName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>space_info.planets.planet_name</code>.
     */
    public String getPlanetName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>space_info.planets.mission</code>.
     */
    public void setMission(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>space_info.planets.mission</code>.
     */
    public String getMission() {
        return (String) get(2);
    }

    /**
     * Setter for <code>space_info.planets.launch</code>.
     */
    public void setLaunch(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>space_info.planets.launch</code>.
     */
    public LocalDate getLaunch() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>space_info.planets.iau_pattern</code>.
     */
    public void setIauPattern(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>space_info.planets.iau_pattern</code>.
     */
    public String getIauPattern() {
        return (String) get(4);
    }

    /**
     * Setter for <code>space_info.planets.moons</code>.
     */
    public void setMoons(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>space_info.planets.moons</code>.
     */
    public String getMoons() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, LocalDate, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, LocalDate, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Planets.PLANETS.ID;
    }

    @Override
    public Field<String> field2() {
        return Planets.PLANETS.PLANET_NAME;
    }

    @Override
    public Field<String> field3() {
        return Planets.PLANETS.MISSION;
    }

    @Override
    public Field<LocalDate> field4() {
        return Planets.PLANETS.LAUNCH;
    }

    @Override
    public Field<String> field5() {
        return Planets.PLANETS.IAU_PATTERN;
    }

    @Override
    public Field<String> field6() {
        return Planets.PLANETS.MOONS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPlanetName();
    }

    @Override
    public String component3() {
        return getMission();
    }

    @Override
    public LocalDate component4() {
        return getLaunch();
    }

    @Override
    public String component5() {
        return getIauPattern();
    }

    @Override
    public String component6() {
        return getMoons();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPlanetName();
    }

    @Override
    public String value3() {
        return getMission();
    }

    @Override
    public LocalDate value4() {
        return getLaunch();
    }

    @Override
    public String value5() {
        return getIauPattern();
    }

    @Override
    public String value6() {
        return getMoons();
    }

    @Override
    public PlanetsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PlanetsRecord value2(String value) {
        setPlanetName(value);
        return this;
    }

    @Override
    public PlanetsRecord value3(String value) {
        setMission(value);
        return this;
    }

    @Override
    public PlanetsRecord value4(LocalDate value) {
        setLaunch(value);
        return this;
    }

    @Override
    public PlanetsRecord value5(String value) {
        setIauPattern(value);
        return this;
    }

    @Override
    public PlanetsRecord value6(String value) {
        setMoons(value);
        return this;
    }

    @Override
    public PlanetsRecord values(Integer value1, String value2, String value3, LocalDate value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlanetsRecord
     */
    public PlanetsRecord() {
        super(Planets.PLANETS);
    }

    /**
     * Create a detached, initialised PlanetsRecord
     */
    public PlanetsRecord(Integer id, String planetName, String mission, LocalDate launch, String iauPattern, String moons) {
        super(Planets.PLANETS);

        set(0, id);
        set(1, planetName);
        set(2, mission);
        set(3, launch);
        set(4, iauPattern);
        set(5, moons);
    }
}
