/*
 * This file is generated by jOOQ.
 */
package org.jooq.test;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.jooq.test.tables.Planets;


/**
 * A class modelling indexes of tables of the <code>space_info</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PLANETS_IAU_PATTERN_UNIQUE = Indexes0.PLANETS_IAU_PATTERN_UNIQUE;
    public static final Index PLANETS_PLANET_NAME_UNIQUE = Indexes0.PLANETS_PLANET_NAME_UNIQUE;
    public static final Index PLANETS_PRIMARY = Indexes0.PLANETS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PLANETS_IAU_PATTERN_UNIQUE = Internal.createIndex("iau_pattern_UNIQUE", Planets.PLANETS, new OrderField[] { Planets.PLANETS.IAU_PATTERN }, true);
        public static Index PLANETS_PLANET_NAME_UNIQUE = Internal.createIndex("planet_name_UNIQUE", Planets.PLANETS, new OrderField[] { Planets.PLANETS.PLANET_NAME }, true);
        public static Index PLANETS_PRIMARY = Internal.createIndex("PRIMARY", Planets.PLANETS, new OrderField[] { Planets.PLANETS.ID }, true);
    }
}
