/*
 * This file is generated by jOOQ.
 */
package org.jooq.test;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.test.tables.Planets;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpaceInfo extends SchemaImpl {

    private static final long serialVersionUID = 1994860256;

    /**
     * The reference instance of <code>space_info</code>
     */
    public static final SpaceInfo SPACE_INFO = new SpaceInfo();

    /**
     * The table <code>space_info.planets</code>.
     */
    public final Planets PLANETS = org.jooq.test.tables.Planets.PLANETS;

    /**
     * No further instances allowed
     */
    private SpaceInfo() {
        super("space_info", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Planets.PLANETS);
    }
}
