/*
 * This file is generated by jOOQ.
 */
package org.jooq.test;


import javax.annotation.Generated;

import org.jooq.test.tables.Planets;


/**
 * Convenience access to all tables in space_info
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>space_info.planets</code>.
     */
    public static final Planets PLANETS = Planets.PLANETS;
}
